In [3]:
import glob
import numpy as np

data_files = glob.glob("./data/events/IC*.txt")
data_file_year = np.array([])
data_day = np.array([])
data_sigmas = np.array([])
data_ra = np.array([])
data_dec = np.array([])
for data_file_name in data_files:
    print("Loading filename: %s" % data_file_name)
    f = open(data_file_name)

    year = int(2011)#data_file_name.split("-")[-2])

    data = np.loadtxt(data_file_name, dtype='float')
    data_file_year = np.append(data_file_year,
                               year * np.ones(len(data), dtype='int'))                                              
    data_day = np.append(data_day, data[:, 0])
    data_sigmas = np.append(data_sigmas, data[:, 2])
    data_ra = np.append(data_ra, data[:, 3])
    data_dec = np.append(data_dec, data[:, 4])
    print(data_sigmas)

np.savez("./processed_data/output_icecube_data.npz",
         data_day=data_day,
         data_sigmas=data_sigmas,
         data_ra=data_ra,
         data_dec=data_dec,
         data_file_year=data_file_year) 

Loading filename: ./data/events/IC86_VII_exp.txt
[0.89 0.35 0.2  ... 0.3  0.21 0.25]
Loading filename: ./data/events/IC59_exp.txt
[0.89 0.35 0.2  ... 1.17 0.5  1.77]
Loading filename: ./data/events/IC86_I_exp.txt
[0.89 0.35 0.2  ... 3.03 0.74 0.2 ]
Loading filename: ./data/events/IC86_V_exp.txt
[0.89 0.35 0.2  ... 1.28 0.92 2.76]
Loading filename: ./data/events/IC79_exp.txt
[0.89 0.35 0.2  ... 0.2  2.04 0.68]
Loading filename: ./data/events/IC86_II_exp.txt
[0.89 0.35 0.2  ... 0.27 0.73 0.2 ]
Loading filename: ./data/events/IC40_exp.txt
[0.89 0.35 0.2  ... 0.61 0.87 1.34]
Loading filename: ./data/events/IC86_III_exp.txt
[0.89 0.35 0.2  ... 1.88 1.31 0.25]
Loading filename: ./data/events/IC86_VI_exp.txt
[0.89 0.35 0.2  ... 0.78 0.2  1.63]
Loading filename: ./data/events/IC86_IV_exp.txt
[0.89 0.35 0.2  ... 0.63 0.2  0.37]
